version: "3"
services:
  wordpress:
    image: wordpress
    ports:
      - "8089:80"
    depends_on:
      - mysql
    environment:
      - WORDPRESS_DB_HOST=mysql
      - WORDPRESS_DB_NAME=wp_db
      - WORDPRESS_DB_USER=root
      - WORDPRESS_DB_PASSWORD=pass1234
    networks:
      wp-network:
        ipv4_address: "10.44.44.40"
  mysql:
    image: mysql
    environment:
      - MYSQL_DATABASE=wp_db
      - MYSQL_ROOT_PASSWORD=pass1234
    networks:
      wp-network:
        ipv4_address: "10.44.44.20"
  phpmyadmin:
    image: phpmyadmin
    ports:
      - "8081:80"
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: pass1234
    networks:
      wp-network:
        ipv4_address: "10.44.44.60"
networks:
  wp-network:
    ipam:
      driver: default
      config:
        - subnet: "10.44.44.0/24"
